version: 0.0
os: linux
files:
  - source: / # Projenin tamamını dağıt
    destination: /home/ec2-user/my-app # EC2'deki hedef dizin
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh # Dağıtım öncesi bağımlılıkları yükle
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/run_start.sh # Uygulamayı başlat
      timeout: 300
      runas: ec2-user