version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/compman
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/run_start.sh
      timeout: 300
      runas: ec2-user
